title: Cresspresso
email: cresspresso@gmail.com
github_username: Cresspresso

realurl: https://cresspresso.github.io
baseurl: ''
permalink: /:categories/:title/
iconsurl: /assets/images/icons/
socialiconsurl: /assets/images/socialsites/
postimagesurl: /assets/images/posts/

stylesheet: /assets/style.css
disqusDebug: false

homepage:
  permalink: /
  group: Cresspresso
  icon: 'green-fern-cresspresso.svg'
  tabicon: 'green-fern-cresspresso-32.png'

include:
- _pages


socialsites:
- 
  title: Bandcamp
  link: https://cresspresso.bandcamp.com/
  icon: 'Music 128.png'
- 
  title: Facebook
  link: https://www.facebook.com/cresspresso
  icon: 'Personal 128.png'
- 
  title: GitHub
  link: https://github.com/Cresspresso
  icon: 'Coding 128.png'
- 
  title: Google+
  link: https://plus.google.com/109854229651423575407
  icon: 'Cresspresso 128.png'
- 
  title: Patreon
  link: https://www.patreon.com/cresspresso
  icon: 'Art 128.png'
- 
  title: SoundCloud
  link: https://soundcloud.com/cresspresso
  icon: 'Music 128.png'
- 
  title: Tumblr
  link: http://cresspresso.tumblr.com/
  icon: 'Gaming 128.png'
- 
  title: Twitch
  link: https://www.twitch.tv/cresspresso
  icon: 'Gaming 128.png'
- 
  title: YouTube
  link: https://www.youtube.com/channel/UCiPzRDLIQYkPJd6xKeDjz9A
  icon: 'Coding 128.png'

emptyarray: []

gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock


