title: Cresspresso
email: cresspresso@gmail.com
github_username: Cresspresso

baseurl: ''
permalink: /:categories/:year/:month/:day/:title/
stylesheet: /assets/style.css
iconsurl: /assets/icons/
baseicon: 'Coding 128.png'

homepage:
  permalink: /

include:
- _pages

socialsites:
- 
  title: Patreon
  link: https://www.patreon.com/cresspresso
- 
  title: YouTube
  link: https://www.youtube.com/channel/UCiPzRDLIQYkPJd6xKeDjz9A
- 
  title: SoundCloud
  link: https://soundcloud.com/cresspresso
- 
  title: Bandcamp
  link: https://cresspresso.bandcamp.com/
- 
  title: Tumblr
  link: http://cresspresso.tumblr.com/
- 
  title: Facebook
  link: https://www.facebook.com/cresspresso
- 
  title: Google+
  link: https://plus.google.com/109854229651423575407
- 
  title: Twitch
  link: https://www.twitch.tv/cresspresso

gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
